# Generated by Django 4.2.9 on 2024-07-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_deleterequest_feedback_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='produit',
            field=models.CharField(default='', max_length=100),
        ),
    ]
